# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapser_real_rcppparallel <- function(x, keep) {
    .Call(`_collapse_collapser_real_rcppparallel`, x, keep)
}

collapser_real_omp <- function(x, keep) {
    .Call(`_collapse_collapser_real_omp`, x, keep)
}

getThreads <- function(max = FALSE) {
    .Call(`_collapse_getThreads`, max)
}

setThreads <- function(n, reset_after_fork = -1L) {
    .Call(`_collapse_setThreads`, n, reset_after_fork)
}

hasOpenMP <- function() {
    .Call(`_collapse_hasOpenMP`)
}

